### ISSUE TITLE
Currency exchange rate

### ISSUE THREAD

**Issue by Emsacras** [PenguiniVogel/BuffUtility#38]
Hello, the currency exchange rate from Yuan to eur is not accurate for a while now.
5280.83 RMB are shown as worth 708.49€ when in fact according to XE data (and buff pricing) its only worth 673.61.
Wouldn't it be possible to get the data elsewhere or updating the rate more often ?
Thanks.
(I lost like 300€ total this month on cashtrading basing my price on that but that's on me i'm a morron i should have double checked :p )

**Comment by PenguiniVogel** [comment]
use a different extension if mine doesnt suit your purpose
