### ISSUE TITLE
Synchronization of prices in favorites and overview

### ISSUE THREAD

**Issue by GODrums** [PenguiniVogel/BuffUtility#8]
The currency feature works very well with market listings. Although currently it does not convert item prices in the 'Favorites' section yet.

Favorited item as listing (conversion by BuffUtility):
![item-listing](https://user-images.githubusercontent.com/21990230/186690200-07ddb6d0-befe-4f7d-a50d-dc7d1173ae0f.png)

Same item in 'Favorites' (conversion by Buff):
![item-Favorites](https://user-images.githubusercontent.com/21990230/186690296-c2e6fb98-ae7a-4bd9-815e-e06ac8de0058.png)

---

Further prices in the overview section of the market listings are also not converted:
![Item-overview](https://user-images.githubusercontent.com/21990230/186691682-f95f3a29-d607-48cd-b041-4de0eb144708.png)
Although this may be way more difficult to implement as prices should be homogenous for all conditions (so either all are converted or none).

**Comment by PenguiniVogel** [comment]
Hey there, thanks for bringing this to my attention.
Conversion in various fields is worked on, there is another topic in the works regarding this, I will make sure to not forget this

**Comment by PenguiniVogel** [comment]
@GODrums If you wish to bring things to my attention sooner, as I don't check my github frequently, feel free to friend me on Discord, most of the inquiries reach me there regarding BuffUtility `Penguini#1234`

**Comment by PenguiniVogel** [comment]
Resolved with https://github.com/PenguiniVogel/BuffUtility/commit/358fac0121d7c21716158a4c0ee8eeeca7c870a5
